Extract all review units from GitHub merge request commits
thesecurereview/policychecker pull request #49
Opened 2021-04-13 01:24 UTC by foliverajr

**This PR introduces**

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Code style update
- [ ] Other, please describe:

**Fixes issue** #42

2021-04-26 19:19 UTC, hmdfsn approved these changes

2021-04-26 20:11 UTC, hmdfsn2 requested changes

2021-04-26 20:11 UTC, hmdfsn2 commented on src/constants.py
> +KEYS_DIR = '/home/fernando/.gnupg'
We should handle different systems not embedding the path in the code.

2021-04-28 19:06 UTC, hmdfsn commented on src/constants.py
> +KEYS_DIR = '/home/fernando/.gnupg'
We will address this issue in a separate PR.

2021-04-28 19:06 UTC, merged